"use client";

import Faq from "./components/faq/faq";
import { Country } from "@/utils/types";
import useSWR from "swr";
import AnswerInput from "./components/answerInput";
import Header from "./components/header";
import { useState } from "react";
import CountryInformation from "./components/countryInformation";
import generateRandomNumber from "@/utils/generateRandomNumber";

async function getCountries() {
  // As new countries are generated by refreshing the page, we need to opt out caching so new data is fetched
  const res = await fetch(
    "https://restcountries.com/v3.1/all?fields=name,capital,flags,currencies,continents,languages,population",
    { cache: "no-store" },
  );

  if (!res.ok) {
    throw new Error("Error fetching data");
  }

  const countries = await res.json();

  // Filter out countries without a capital like Antarctica
  const countriesWithCapital = countries.filter((country: Country) => country.capital && country.capital.length > 0);

  return countriesWithCapital;
}

export default function Home() {
  const [streakCount, setStreakCount] = useState(0);
  const [alreadyGuessedCapitals, setAlreadyGuessedCapitals] = useState<string[]>([]);

  const fetcher = (url: string) => fetch(url).then((res) => res.json());
  const { data, error, isLoading } = useSWR(
    "https://restcountries.com/v3.1/all?fields=name,capital,flags,currencies,continents,languages,population",
    fetcher,
  );

  if (error) {
    return <div>Error loading data</div>;
  }

  if (!data && isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>No data available</div>;
  }

  const country = data[generateRandomNumber(data.length)];

  return (
    <main className="flex flex-col items-center px-2 md:px-0">
      <Header streakCount={streakCount} />
      <CountryInformation country={country} />
      <AnswerInput
        answer={country.capital[0]}
        setStreakCount={setStreakCount}
        streakCount={streakCount}
        setAlreadyGuessedCapitals={setAlreadyGuessedCapitals}
      />
      <Faq />
    </main>
  );
}
